let myAge = 2;
let earlyYears = 2;
earlyYears *= 10.5;
console.log(earlyYears);
let laterYears = myAge - 2;
console.log(myAge);
console.log(laterYears);
laterYears *= 4;
console.log (laterYears);
let myAgeInDogYears = earlyYears + laterYears;
console.log(myAgeInDogYears);
myName = 'Frida Kahlo'.toLowerCase();
console.log(myName);
console.log(`My name is ${myName}. I am ${myAge} years old in human years which is ${myAgeInDogYears} years old in dog years.`);